### ISSUE TITLE
module Appregistry is not a registered callable

### ISSUE THREAD

**Issue by zhangw1956** [smallnew/react-native-multibundler#1]
遇到了这个问题，请问该怎么解决

**Comment by zhangw1956** [comment]
module Appregistry is not a registered callable（calling runApplication）

**Comment by smallnew** [comment]
iOS还是android的？使用例子出现的还是自己集成出现的？

**Comment by zhangw1956** [comment]
> iOS还是android的？使用例子出现的还是自己集成出现的？

windows环境下打包配置文件反斜杠的问题，已解决
