### ISSUE TITLE
基础包用--dev true 打出的包运行会报错

### ISSUE THREAD

**Issue by hwzhang92** [smallnew/react-native-multibundler#10]
node ./node_modules/react-native/local-cli/cli.js bundle --platform ios --dev true --entry-file platformDep.js --bundle-output ./ios/platform.ios.bundle --assets-dest ./ios/ --config {绝对路径}/platform57.config.js
--dev 改成true，打出的基础包，iOS加载会报错，如下图:
![image](https://user-images.githubusercontent.com/12094526/51373933-6c459d00-1b3c-11e9-9092-6b4b81ddd67e.png)

**Comment by Jekiwijaya** [comment]
That's because of https://github.com/facebook/metro/blob/master/packages/metro/src/lib/polyfills/require.js#L138-L148

https://github.com/smallnew/react-native-multibundler/blob/master/platform57.config.js#L2-L16
to fix, createModuleIdFactory must return a number type.

**Comment by smallnew** [comment]
有个不完美的解决方法，打开基础包js 文本，在开头修改var __DEV__=true,变为var __DEV__=false,..不过这样可能会缺失一些RN的开发特性

**Comment by seuzxh** [comment]
> 有个不完美的解决方法，打开基础包js 文本，在开头修改var **DEV**=true,变为var **DEV**=false,..不过这样可能会缺失一些RN的开发特性

如果使用拆包方式的话就意味着要放弃 dev==true 的编译方式吗？

**Comment by smallnew** [comment]
> > 有个不完美的解决方法，打开基础包js 文本，在开头修改var **DEV**=true,变为var **DEV**=false,..不过这样可能会缺失一些RN的开发特性
> 
> 如果使用拆包方式的话就意味着要放弃 dev==true 的编译方式吗？

你可以写两套加载逻辑，一套是发布时候用的拆包，一套是测试时候按普通方式加载js包

**Comment by smallnew** [comment]
新的版本可以使用数字作为moduleId，这样可以解决打dev为true的包运行出错的问题，新的版本也添加了debug功能
