### ISSUE TITLE
问下大佬  我如果在网上下载bundle报  这个getScriptPath是不是我下载bundle的地址？请回复一下，谢谢

### ISSUE THREAD

**Issue by lufan6** [smallnew/react-native-multibundler#13]

**Comment by smallnew** [comment]
不是，是本地地址，没有支持网上下载功能

**Comment by lufan6** [comment]
你好，react-native_multibundler_ui-darwin-x64无法解压啊/能回复一下吗




| |
15662666890
|
|
15662666890@163.com
|
签名由网易邮箱大师定制

**Comment by smallnew** [comment]
我这边没发现这个问题
你直接单独下载这个zip包看看
https://github.com/smallnew/react-native-multibundler/blob/master/package-ui-bin/react-native_multibundler_ui-darwin-x64.zip

**Comment by lufan6** [comment]
您好问一下图片不显示，怎么解决？麻烦回复一下




| |
15662666890
|
|
15662666890@163.com
|
签名由网易邮箱大师定制


在2019年03月19日 17:17，smallnew<notifications@github.com> 写道：

我这边没发现这个问题
你直接单独下载这个zip包看看
https://github.com/smallnew/react-native-multibundler/blob/master/package-ui-bin/react-native_multibundler_ui-darwin-x64.zip

**Comment by lufan6** [comment]
你好找不到com.facebook.react.devsupport.JSException: Can't find variable: __d知道是什么问题吗。麻烦回复一下 谢谢


| |
15662666890
|
|
15662666890@163.com
|
签名由网易邮箱大师定制


在2019年03月20日 08:48，15662666890<15662666890@163.com> 写道：
您好问一下图片不显示，怎么解决？麻烦回复一下




| |
15662666890
|
|
15662666890@163.com
|
签名由网易邮箱大师定制


在2019年03月19日 17:17，smallnew<notifications@github.com> 写道：

我这边没发现这个问题
你直接单独下载这个zip包看看
https://github.com/smallnew/react-native-multibundler/blob/master/package-ui-bin/react-native_multibundler_ui-darwin-x64.zip

**Comment by lufan6** [comment]
您好，我把bundle包放在本地sd中加载图片不显示，放到assets目录下就显示，问一下什么原因。麻烦回复一下，谢谢


| |
15662666890
|
|
15662666890@163.com
|
签名由网易邮箱大师定制


在2019年03月20日 10:27，15662666890<15662666890@163.com> 写道：
你好找不到com.facebook.react.devsupport.JSException: Can't find variable: __d知道是什么问题吗。麻烦回复一下 谢谢


| |
15662666890
|
|
15662666890@163.com
|
签名由网易邮箱大师定制


在2019年03月20日 08:48，15662666890<15662666890@163.com> 写道：
您好问一下图片不显示，怎么解决？麻烦回复一下




| |
15662666890
|
|
15662666890@163.com
|
签名由网易邮箱大师定制


在2019年03月19日 17:17，smallnew<notifications@github.com> 写道：

我这边没发现这个问题
你直接单独下载这个zip包看看
https://github.com/smallnew/react-native-multibundler/blob/master/package-ui-bin/react-native_multibundler_ui-darwin-x64.zip

**Comment by smallnew** [comment]
https://github.com/smallnew/react-native-smartassets
