### ISSUE TITLE
Redux在分包中怎么使用的呢？

### ISSUE THREAD

**Issue by cmconan** [smallnew/react-native-multibundler#14]
谢谢大神分享的代码O(∩_∩)O
我的项目中使用了Redux，分包的时候是共用一份store吗？
还是建多个store，各用各的？
其中有一个reducer是用来做主题颜色切换的，所有的业务包都需要用到，这样的话只能共用一个store才能做到了。有没有更好的方式呢？

**Comment by smallnew** [comment]
共用一份store

**Comment by robi027** [comment]
@cmconan @smallnew can you give example how can we share a store between bundle ?

**Comment by cmconan** [comment]
@robi027 共用store放在基础包内，加载时不管加载哪个业务包，都先判断并加载基础包即可

**Comment by robi027** [comment]
@cmconan thank you, currently i've implemented like your suggestion and it works
