### ISSUE TITLE
iOS打业务包后，图片只能引用到基础包asserts里面图片，请问需要怎么处理

### ISSUE THREAD

**Issue by GideonLiu** [smallnew/react-native-multibundler#15]
iOS打业务包后，图片只能引用到基础包asserts里面图片，请问需要怎么处理
通过alert可以看到图片路径是基础包asserts里面图片，而不是业务包里面的图片路径，从而导致图片显示不出来

**Comment by smallnew** [comment]
解决了么？你这样描述我也没法定位问题

**Comment by rabholly** [comment]
我是在native下载完包后把业务包里的图片都拷贝到基础包路径

**Comment by smallnew** [comment]
> 我是在native下载完包后把业务包里的图片都拷贝到基础包路径

RN读资源确实只能在一个目录下读取，如果要多路径读取的话只能Hook RN的读资源方法

**Comment by liyanfei1004774105** [comment]
> > 我是在native下载完包后把业务包里的图片都拷贝到基础包路径
> 
> RN读资源确实只能在一个目录下读取，如果要多路径读取的话只能Hook RN的读资源方法

您好,具体怎么做的,能否分享一下?

**Comment by liyanfei1004774105** [comment]
get icon_delete() {
        return require('./icon_delete.png')
    },
我是这样取的图片,打包之后,图片不显示,大神给提供个解决方案吧^_^

**Comment by liyanfei1004774105** [comment]
ios 
加载 Native图片是显示的  require 去加载的时候打包不显示

**Comment by liyanfei1004774105** [comment]
> 我是在native下载完包后把业务包里的图片都拷贝到基础包路径

你好,我也碰到同样的问题,能否分享一下具体做法???

**Comment by zuifeng1776** [comment]
Showing Recent Messages
:-1: Library not found for -lRCTGeolocation
我打开iOS 项目，显示这个错，你们遇到过吗？

**Comment by smallnew** [comment]
新的master分支上已经对资源隔离做了处理
