### ISSUE TITLE
使用multibundler_cmd.txt中方法打包，包不能正常使用

### ISSUE THREAD

**Issue by hxkuan** [smallnew/react-native-multibundler#16]
问题1: 使用介绍的方法打包，打出的platform包与原来的包有却别。这是正常的吗？
问题2: 打出的buz包，与原来包相比少了几个模块！且无法正常运行

**Comment by hxkuan** [comment]
自己打出的bundle，业务1和业务2居然还能运行，业务3的bundle就直接崩溃了
报错 com.facebook.react.common.JavascriptException: Requiring unknown module "node_modules_react-navigation_src_react-navigation"., stack:

**Comment by smallnew** [comment]
1、只要打出来的包能正常运行就正常，因为原来的包我是用UI打包打的
2、业务3包含了react-navigation模块，需要UI打包计算依赖的，所以像业务3这种情况必须用UI打包
