### ISSUE TITLE
debug release 打包依赖库问题

### ISSUE THREAD

**Issue by sanshanchuns** [smallnew/react-native-multibundler#19]
package.json

{
  "name": "App",
  "version": "5.3.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
  },
  "dependencies": {
    "club-rn-base": "^3.0.1"
  },
  "devDependencies": {
    "babel-jest": "22.4.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-react-native": "4.0.0",
    "eslint": "^5.7.0",
    "jest": "22.4.2",
    "metro-react-native-babel-preset": "^0.52.0",
    "react-test-renderer": "16.0.0",
    "redux-logger": "^3.0.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

基础包
"bundle-ios-platform": "node ./node_modules/react-native/local-cli/cli.js bundle --platform ios --dev false --entry-file platformDep.js --bundle-output ios/bundle/platform.jsbundle --assets-dest ./ios/ --config $(pwd)/platform57.config.js",

业务包
"bundle-ios-buz": "node ./node_modules/react-native/local-cli/cli.js bundle --platform ios --dev false --entry-file index.js --bundle-output ios/bundle/buz.jsbundle --assets-dest ./ios/ --config $(pwd)/buz57.config.js",

其中基础包配置 platformEmptyDefaultExport.js 中 必须要
import 'redux-logger'
因为业务包里用到了这个库，但这个库本应该在dev中，虽然业务包脚本指定了 --dev false，但为什么业务包中还是会用到呢？
我的理解是 如果指定 --dev false, 那么打包的时候会略过。
可能是因为现在业务包的配置没能忽略 devDependencies, 如果是这样，怎么配置忽略 devDependencies?

**Comment by smallnew** [comment]
在devDependencies并不代表这个module不会被打进去，在dependencies内声明也不代表这个module一定会被打进去
