### ISSUE TITLE
platformEmptyDefaultExport

### ISSUE THREAD

**Issue by zhumoyong** [smallnew/react-native-multibundler#21]
platformEmptyDefaultExport  这个有什么用途呢

**Comment by zhumoyong** [comment]
![image](https://user-images.githubusercontent.com/8111663/53724439-da53e280-3ea4-11e9-86d5-0b8e585938b3.png)

**Comment by smallnew** [comment]
platformEmptyDefaultExport一般情况下没有用，就是为了防止基础包过于简单导至babel_runtime_helpers_interopRequireDefault没有引入

**Comment by smallnew** [comment]
你错误的配置发出来看看，package.json和命令行执行方式

**Comment by zhumoyong** [comment]
![image](https://user-images.githubusercontent.com/8111663/54005566-e2f23480-4194-11e9-9bc4-e29283f315c1.png)
问题已解决，在platformDep.js中缺哪个要引入哪个，不能仅仅只引入一级目录的，
import 'redux-persist/es/integration/react'
