### ISSUE TITLE
babel_runtime_helpers_taggedTemplateLiteralLoose

### ISSUE THREAD

**Issue by zdongcoding** [smallnew/react-native-multibundler#25]
com.facebook.react.common.JavascriptException: Requiring unknown module "node_modules_@babel_runtime_helpers_taggedTemplateLiteralLoose".

**Comment by smallnew** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
在基础包添加``反斜杠表达式试试，由于基础包没有这个特性就没有就没被打进去

**Comment by zdongcoding** [comment]
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
> 在基础包添加``反斜杠表达式试试，由于基础包没有这个特性就没有就没被打进去

还是不行， 我们想是把第三方公有库 打到 platform里面 报这个错

**Comment by smallnew** [comment]
这个是在运行时候报的错，而不是在打包时候报错吧

**Comment by zdongcoding** [comment]
打包  没有问题， 问题都是发生在  运行时

**Comment by zdongcoding** [comment]
顺便 问下  你们 有木有打  第三方 例如  redux   打到 platform 里面 好像很多坑啊

**Comment by smallnew** [comment]
打过，没什么问题，你这个报错因为你业务包某些babel属性基础包没有，如果知道是什么属性加上就行

**Comment by zdongcoding** [comment]
那你怎么解决 依赖的依赖 也就是子依赖问题  打 第三方包 有子依赖的话  用 一个 import  无法加载 只依赖的库，导致  platform  加载失败

**Comment by smallnew** [comment]
把buz57.config.js中postProcessModulesFilter函数的判断改成如下
if(module['path'].indexOf(pathSep+'node_modules'+pathSep)>0){
        if('js'+pathSep+'script'+pathSep+'virtual'==module['output'][0]['type']){
            return true;
        }
        if(module['path'].indexOf(pathSep+'node_modules'+pathSep+'@babel'
        +pathSep+'runtime'+pathSep+'helpers')>0){//添加这个判断，让@babel/runtime打进包去
          return true;
        }
        return false;
    }

**Comment by zdongcoding** [comment]
好的， 谢谢，  bz 的 bundle 能打进去， 但是  platform.android.bundle 就加载失败了，因为 platform.android.bundle 可能需要这个 @babel/runtime/helpers/     正常都可以运行， 但是我们把第三方基础库打包到  platform里面  才报这个错

**Comment by smallnew** [comment]
问题已经修复，见最新版本
