### ISSUE TITLE
> 我是在native下载完包后把业务包里的图片都拷贝到基础包路径

### ISSUE THREAD

**Issue by liyanfei1004774105** [smallnew/react-native-multibundler#26]
> 我是在native下载完包后把业务包里的图片都拷贝到基础包路径

你好,我也碰到同样的问题,能否分享一下具体做法???

_Originally posted by @liyanfei1004774105 in https://github.com/smallnew/react-native-multibundler/issues/15#issuecomment-475132532_

**Comment by shenwangjie** [comment]
图片的问题是存在bug的，可能是机制只能加载第一次包的图片也就是基础包，所以业务包里面的图片都加载不出来

**Comment by smallnew** [comment]
请将基础包、业务包、资源都放在同一个目录下

**Comment by star-heng** [comment]
@smallnew  我把基础包、业务包、资源(res文件)都放在同一个目录下, 但是这样还是不显示.

**Comment by smallnew** [comment]
新的版本可以放在完全不同的目录下了
