### ISSUE TITLE
业务包打包依赖问题，使用react-navigation@x3出现的问题

### ISSUE THREAD

**Issue by liuchengjian** [smallnew/react-native-multibundler#27]
界面就是一个简单的跳转
然后根据文档进行分包操作，通过buz-ui.config.js，命令行进行打包，相继出现找不到第三方包的错，通过issues找到添加对应的第三方依赖
![QQ图片20190327164513](https://user-images.githubusercontent.com/23090778/55061880-c704f300-50af-11e9-907d-585cb7029b46.png)
之后重新打包，出现以下的错误
![image](https://user-images.githubusercontent.com/23090778/55062159-56aaa180-50b0-11e9-87a8-a853f0148aeb.png)，不知道什么原因

**Comment by smallnew** [comment]
优先使用UI界面打包，详见文档
