### ISSUE TITLE
windows端Ui工具没有配置第三方依赖呢？或者怎么配置第三放依赖呢

### ISSUE THREAD

**Issue by liuchengjian** [smallnew/react-native-multibundler#28]
![image](https://user-images.githubusercontent.com/23090778/55133610-3be43580-5161-11e9-827d-91ba65896e31.png)

**Comment by boyrt** [comment]
mac 也一样的，
![image](https://user-images.githubusercontent.com/20635526/55776038-f19e7500-5acd-11e9-8882-912dc875c52f.png)

**Comment by smallnew** [comment]
package.json中没有第三方库的话就不会出现模块依赖，业务包打包前需要先打包基础包
