### ISSUE TITLE
执行ios基础打包出现问题

### ISSUE THREAD

**Issue by lixiaozhangme** [smallnew/react-native-multibundler#3]
SHA-1 for file /Users/lixiaozhang/desktop/workspace/react-native-multibundler/platformDep.js is not computed

![image](https://user-images.githubusercontent.com/19645470/47710221-3398d480-dc6d-11e8-88ce-3be54e4b7c2b.png)

**Comment by smallnew** [comment]
用的什么系统？你的workspace目录是不是一个symlink而不是真实目录？

**Comment by smallnew** [comment]
如果你出现这个问题，你在这个目录下新初始化一个新的0.57版本的rn新项目应该也没法打包

**Comment by lixiaozhangme** [comment]
这个不是一个symlink，是真是目录，这个目录下有很多的工程包括rn项目

**Comment by lixiaozhangme** [comment]
其他rn项目都能运行的，而且你的这个项目我直接运行没问题，就是打包有问题

**Comment by smallnew** [comment]
那你用的是windows？android打包没问题？

**Comment by lixiaozhangme** [comment]
我用的mac，就试了一下ios,打基础包，就编译不过了

**Comment by smallnew** [comment]
<img width="649" alt="141428 2x" src="https://user-images.githubusercontent.com/10057364/47769619-6eefdd80-dd17-11e8-91c2-67bfd8cac371.png">
我这边下载下来自己试了没问题，我也是mac，以你现在给的信息我找不到问题在哪
