### ISSUE TITLE
相同名称的业务包从网络重新加载,界面不刷新,大神有没有碰到这种使用场景,怎么解决的

### ISSUE THREAD

**Issue by liyanfei1004774105** [smallnew/react-native-multibundler#32]
相同名称的业务包从网络重新加载,界面不刷新,大神有没有碰到这种使用场景,怎么解决的

**Comment by smallnew** [comment]
没见过这种场景，按道理名称不应该一样

**Comment by liyanfei1004774105** [comment]
> 没见过这种场景，按道理名称不应该一样

我们要做的是自己控制 业务包更新,所以就有从网络重新加载业务包的需要,我先做成不同的版本 bundle 包名不同吧!有了方法再改回来

**Comment by liuchengjian** [comment]
> 先做成不同的版本 bundle 包名不同

相同的名称可以实现重新加载业务包实时更新吗？还是要调什么方法

**Comment by liuchengjian** [comment]
> 没见过这种场景，按道理名称不应该一样
> 
> 我们要做的是自己控制 业务包更新,所以就有从网络重新加载业务包的需要,我先做成不同的版本 bundle 包名不同吧!有了方法再改回来
