### ISSUE TITLE
Requiring unknown module "node_modules_@babel_runtime_helpers_interopRequireDefault"

### ISSUE THREAD

**Issue by liuyankai1990** [smallnew/react-native-multibundler#34]
Requiring unknown module "node_modules_@babel_runtime_helpers_interopRequireDefault"

大佬，打包之后加载业务包，提示这个错误，是什么原因呢？

**Comment by gzqreder** [comment]
我这边报的错误是
Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `.../platform.js`: Module `@babel/runtime/helpers/interopRequireDefault` does not exist in the Haste module map

**Comment by smallnew** [comment]
基础包中
import这个文件platformEmptyDefaultExport.js

**Comment by liuyankai1990** [comment]
> 基础包中
 import这个文件platformEmptyDefaultExport.js

基础包中已经import这个文件了，但是还是报这个错

**Comment by ruyadelaosan** [comment]
dalao，the same error with liuyankai1990 i have met. 
RN@0.59.4

**Comment by smallnew** [comment]
参考https://github.com/smallnew/react-native-multibundler/issues/25，里面的方法先试试

**Comment by ruyadelaosan** [comment]
我基础bundle中未包含node_modules_@babel_runtime_helpers_xxx依赖。后来发现是我的基础.js文件写法有问题，具体如下：
- [错误] import "react";
- [正确] import React,{Component} from "react";
@smallnew 感谢指导

**Comment by smallnew** [comment]
问题已修复

**Comment by leeeGreat** [comment]
这个问题解决了吗？我这里是demo没啥问题，只要一引入三方库，就会报这个

> Requiring unknown module "node_modules_@babel_runtime_helpers_interopRequireDefault"
> 
> 大佬，打包之后加载业务包，提示这个错误，是什么原因呢？
RN版本0.64.3，demo基础包、业务包打包都没问题，但是只要一引入react-navigation这个三方库，就报这个错，能看到这个错的前提是 useIndex 置为了false，不然看到的是Requiring unknown module xxx,xxx为数字

**Comment by vincent-cihan** [comment]
> 这个问题解决了吗？我这里是demo没啥问题，只要一引入三方库，就会报这个
> 
> > Requiring unknown module "node_modules_@babel_runtime_helpers_interopRequireDefault"
> > 大佬，打包之后加载业务包，提示这个错误，是什么原因呢？
> > RN版本0.64.3，demo基础包、业务包打包都没问题，但是只要一引入react-navigation这个三方库，就报这个错，能看到这个错的前提是 useIndex 置为了false，不然看到的是Requiring unknown module xxx,xxx为数字

请问 这个问题最后时怎么解决的
