### ISSUE TITLE
大佬，请教一下可以业务包A调用业务包B里的js文件吗？

### ISSUE THREAD

**Issue by Armyoftheworld** [smallnew/react-native-multibundler#36]
比如我这边有三个包，一个基础包，两个业务包A和B，我现在的需求是业务包A里面需要引用业务包B里的js文件，请问可以这样吗？还是说要先加载业务包B，然后在加载业务包A，这样就可以？

**Comment by smallnew** [comment]
可以啊

**Comment by Armyoftheworld** [comment]
请问可以的话，是不是有什么限制条件？因为我现在业务包A引用业务包B里的js文件报错了，提示找不到这个文件

**Comment by smallnew** [comment]
在这个项目中模块是按路径名字命名的，如果业务包A引用了业务包B的js文件，那这个js文件也会被打到业务包A去，按道理不会找不到文件
如require('B0.js')这样不可以，你可以在基础模块文件中添加一个模块注册功能，把业务B里面要引用的js模块注册到公共区中，然后业务包A再去做引用。

**Comment by Armyoftheworld** [comment]
业务包B的js文件没有打到业务包A中，因为我这边给过滤掉了，因为我就是想在运行的时候业务包A直接引用业务包B，而且我特地先加载业务包B，然后业务包A运行的时候报错了，提示找不到js文件

**Comment by Armyoftheworld** [comment]
不好意思，我发现好像是可以的，我用你项目里的demo发现是可以的，就是先加载业务包B，然后在加载业务包A，能找到B中的js文件

**Comment by Armyoftheworld** [comment]
我还想请教一个问题，ScriptLoadUtil.loadScriptFromAsset(getApplicationContext(), instance, scriptPath, false);这个方法，为什么最后一个参数传true，RN的界面不显示，一直白屏，也没有相关的日志，是因为一直在加载JS代码所以卡在那儿吗？

**Comment by smallnew** [comment]
这个参数具体要看rn的源代码，源代码中这个参数也是false，具体的参数左右看rn源代码

**Comment by Armyoftheworld** [comment]
谢谢！
