### ISSUE TITLE
只能加载一个bundle包

### ISSUE THREAD

**Issue by jwb1220** [smallnew/react-native-multibundler#38]
我照着你这样写只能加载一个业务包，加载第二个的时候就会报 Application has not been registered. 请问可能的问题有哪些

**Comment by jwb1220** [comment]
好像是我命令打包的时候那个入口index文件是同一个，只是注释了不同的业务js文件

**Comment by ShiYongjieGitHub** [comment]
我打出来的业务包怎么都只有2kb？
