### ISSUE TITLE
Requiring unknown module "node_modules_@babel_runtime_helpers_initializerDefineProperty".

### ISSUE THREAD

**Issue by liuyankai1990** [smallnew/react-native-multibundler#39]
![image](https://user-images.githubusercontent.com/10486294/56861747-7fd39000-69d6-11e9-8c08-e29b6c454bc5.png)

**Comment by smallnew** [comment]
参考https://github.com/smallnew/react-native-multibundler/issues/25，里面的方法先试试

**Comment by smallnew** [comment]
用最新版本打包
