### ISSUE TITLE
platformDep.js

### ISSUE THREAD

**Issue by LiuQiulin** [smallnew/react-native-multibundler#40]
var _ = require('lodash');
Text.render = _.wrap(Text.render, function (func, ...args) {
    let originText = func.apply(this, args)
    return React.cloneElement(originText, {allowFontScaling: false})
})

请问platformDep.js中这段代码的作用是什么？望不吝赐教

**Comment by smallnew** [comment]
只是让Text控件的字体大小不跟随系统变化，跟拆包没关系
