### ISSUE TITLE
图片加载的问题以及第三方库的问题

### ISSUE THREAD

**Issue by shenwangjie** [smallnew/react-native-multibundler#42]
感觉涉及这两个业务包根本没有他的功能了，我提到的这两个都只能放在基础包里面。。。或许只能修改源码了吧！

**Comment by star-heng** [comment]
所以, 这边有解决方案么?
更新业务包之后,如果不能加载之前的icon, 那这个分包功能就不好弄了.

**Comment by star-heng** [comment]
图片问题: 当app去加载native下载的业务包bundle的时候(不是apk里面的bundle文件), 界面的icon是不显示的.

**Comment by smallnew** [comment]
已经解决了拆包后分别加载的方案，到新的master分支下查看新的代码
