### ISSUE TITLE
热更新问题

### ISSUE THREAD

**Issue by gaoyangclub** [smallnew/react-native-multibundler#47]
使用codepush热更新，更新完的assets中的图片无法加载，怎么解决跨域问题

**Comment by smallnew** [comment]
这个需要你改resolveAssetSource，你可以在各个包中的全局变量中设置bundle路径，根据路径去加载资源，我这个工程暂不会提供这个功能，如果你不想魔改你可以参考react-native-smartassets去hook。

**Comment by gaoyangclub** [comment]
在android项目里面ReactInstanceManager被做成单例，只能存放一个codepush package用来更新通用bundle，那其他业务bundle如何切换codepush package唤起热更新

**Comment by smallnew** [comment]
code push对于多bundle热更新是不支持的，如果你要支持的话最好自己下载bundle包自己解压，这个换其他拆包方案都是一样，你只能二选一，要么codepush加不拆包，要么拆包自己写热更新
