### ISSUE TITLE
如何判断某个页面属于哪个业务包？

### ISSUE THREAD

**Issue by superzcj** [smallnew/react-native-multibundler#49]
你好，有个问题请教一下。

在有多个业务包的情况下，每个业务包内都有几个页面，那么如何判断某个页面属于哪个业务包？这样根据要进入页面加载对应的业务包。按Demo的做法是在原生侧写死了业务包和对应的页面，这样会限制在js侧动态添加、删除页面，是否能支持在打开RN页面之前，先从js侧读取最新的业务包-页面对应表，然后再加载对应的业务包？

**Comment by smallnew** [comment]
你可以使用intent传递参数到activity，oncreate读出业务包信息
