### ISSUE TITLE
安卓下进入后台再返回应用时崩溃(recreateReactContextInBackgroundInner)

### ISSUE THREAD

**Issue by waynehong** [smallnew/react-native-multibundler#5]
离开应用后，再回到应用，就报java.lang.AssertionError: createReactContextInBackground should only be called when creating the react application for the first time. When reloading JS, e.g. from a new file, explicitlyuse recreateReactContextInBackground。

**Comment by smallnew** [comment]
用的自带demo崩溃？

**Comment by waynehong** [comment]
我注释掉 mainActivity.java 20行
reactInstanceManager.createReactContextInBackground();//这里会先加载基础包platform.android.bundle，也可以不加载
就没问题了
