### ISSUE TITLE
 Showing Recent Messages :-1: Library not found for -lRCTGeolocation

### ISSUE THREAD

**Issue by zuifeng1776** [smallnew/react-native-multibundler#51]
iOS 打开的时候，显示这个报错

**Comment by afeichuanqi** [comment]
你好 你在使用这个分包吗

**Comment by loimh** [comment]
你好,请问这个问题解决了吗

**Comment by reylen** [comment]
![image](https://user-images.githubusercontent.com/7260456/71505020-965c1f00-28b6-11ea-9511-d16c77f9ca88.png)
删掉剩下这两个就好了

**Comment by smallnew** [comment]
最新的rn版本都用pod来管理了，请参照最新的rn文档
