### ISSUE TITLE
关于打包

### ISSUE THREAD

**Issue by xiongyoudou** [smallnew/react-native-multibundler#53]
作者您好，您当前在工程中打好的几个bundle，它们分别都是只包含各自业务的js代码吗？在业务2中有引用业务1的全局变量，此时业务1的js代码有在业务2的bundle中吗?

**Comment by smallnew** [comment]
引用了全局变量，但没引用业务1的js文件，因此业务1的js代码不会存在于业务2的bundle中，不过实际中开发中需要管理好各自的引用

**Comment by xiongyoudou** [comment]
您好，我看了您代码，然后原生OC那边只是加载了platform.ios.bundle，但是没有看到哪里有加载另外几个bundle，它们的加载时机是什么时候呢？或者它们是在什么时候合并的吗？在代码里面没有看到，然后也没有看到相关资料

**Comment by smallnew** [comment]
没有合并的动作，其他业务bundle也是直接加载的，新的master分支iOS工程结构更清晰，你可以去看看
