### ISSUE TITLE
安卓打包release版本后无法运行

### ISSUE THREAD

**Issue by Aptx4869-xd** [smallnew/react-native-multibundler#57]
![1569482485115](https://user-images.githubusercontent.com/8141398/65667026-74fa5580-e071-11e9-8cfa-b11e48526761.jpg)

**Comment by Aptx4869-xd** [comment]
不知道为什么debug版本运行是正常的，打包release就一直这个错误 @smallnew

**Comment by Aptx4869-xd** [comment]
@smallnew 你好，我测试了下，打包release版本，加载基础包会出现上图这个问题，debug的时候是正常，问下你这边打包的时候会出现这个吗？😂

**Comment by star-heng** [comment]
MainApplication中的 getUseDeveloperSupport返回false
@Aptx4869-xd  你要再看一遍demo和说明文档

**Comment by Aptx4869-xd** [comment]
@star-heng 我是返回false的，就是根据demo里写的，编译release版本后运行就一直报这个错误，debug的编译运行是没问题的
<img width="497" alt="WX20191009-172042@2x" src="https://user-images.githubusercontent.com/8141398/66468778-50629c80-eab9-11e9-9732-1762904af55a.png">

**Comment by star-heng** [comment]
两个bundle文件都有? 确定配置没问题?

**Comment by Aptx4869-xd** [comment]
@star-heng 是的，配置上没问题的，我debug都能编译跑起来。
![1570613269004](https://user-images.githubusercontent.com/8141398/66469347-3f665b00-eaba-11e9-8869-716bc403939d.jpg)
<img width="696" alt="WX20191009-172704@2x" src="https://user-images.githubusercontent.com/8141398/66469348-3f665b00-eaba-11e9-8748-ba5feae32a90.png">

**Comment by star-heng** [comment]
MainActivity配置的不对吧
应该是这样的
    @Override
    protected String getScriptPath() {
        return "index.android.bundle";
    }

**Comment by Aptx4869-xd** [comment]
我在父类里吧getScriptPath改成了getBundleName,这个会有影响的吗？ @star-heng

**Comment by Aptx4869-xd** [comment]
<img width="871" alt="WX20191009-173622@2x" src="https://user-images.githubusercontent.com/8141398/66469915-56597d00-eabb-11e9-89ec-bb1b0774a199.png">

**Comment by star-heng** [comment]
检查一下:
MainApplication中的方法 getJSBundleFile注释掉
MainActivity的父类中有这个方法么?  protected abstract String getBundleName();

**Comment by Aptx4869-xd** [comment]
@star-heng 父类里我有写这个方法的，application里我没有重写getJSBundleFile
<img width="610" alt="WX20191009-174353@2x" src="https://user-images.githubusercontent.com/8141398/66470634-90774e80-eabc-11e9-8173-eec69054436a.png">
<img width="759" alt="WX20191009-174424@2x" src="https://user-images.githubusercontent.com/8141398/66470636-910fe500-eabc-11e9-8aa7-d9e247a5fc01.png">

**Comment by Aptx4869-xd** [comment]
项目其他地方应该不用什么特殊配置的是吗？这个项目是我自己新建，不是在demo的基础上迭代修改的

**Comment by star-heng** [comment]
那应是这个问题了, 
你把 app/build.gradle中的  apply from: "../../node_modules/react-native/react.gradle"
这行注释掉.

**Comment by Aptx4869-xd** [comment]
@star-heng 好的，谢谢，我把这个注释了再打包release版本就可以跑起来了

**Comment by star-heng** [comment]
我之前也遇到这个问题, 一时没想起来...

**Comment by Aptx4869-xd** [comment]
@star-heng 哈哈，还是很感谢

**Comment by star-heng** [comment]
没事没事
