### ISSUE TITLE
iOS工程跑不起来

### ISSUE THREAD

**Issue by vanvanj** [smallnew/react-native-multibundler#6]
▸ Copying /Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/ReactCommon/privatedata/PrivateDataBase.h
▸ Compiling PrivateDataBase.cpp
▸ Analyzing PrivateDataBase.cpp
▸ Building library libprivatedata.a
▸ Running script 'Install Third Party'
▸ Compiling fast-dtoa.cc

❌  error: Build input file cannot be found: '/Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/fast-dtoa.cc'

▸ Compiling double-conversion.cc

❌  error: Build input file cannot be found: '/Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/double-conversion.cc'

▸ Compiling fixed-dtoa.cc

❌  error: Build input file cannot be found: '/Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/fixed-dtoa.cc'

▸ Compiling strtod.cc

❌  error: Build input file cannot be found: '/Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/strtod.cc'

▸ Compiling diy-fp.cc

❌  error: Build input file cannot be found: '/Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/diy-fp.cc'

▸ Compiling cached-powers.cc

❌  error: Build input file cannot be found: '/Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/cached-powers.cc'

▸ Compiling bignum.cc

❌  error: Build input file cannot be found: '/Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/bignum.cc'

▸ Compiling bignum-dtoa.cc

❌  error: Build input file cannot be found: '/Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/bignum-dtoa.cc'

** BUILD FAILED **

The following build commands failed:

	CompileC /Users/ryan/Downloads/react-native-multibundler-master/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fast-dtoa.o /Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/fast-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ryan/Downloads/react-native-multibundler-master/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/double-conversion.o /Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/double-conversion.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ryan/Downloads/react-native-multibundler-master/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fixed-dtoa.o /Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/fixed-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ryan/Downloads/react-native-multibundler-master/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/strtod.o /Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/strtod.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ryan/Downloads/react-native-multibundler-master/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/diy-fp.o /Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/diy-fp.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ryan/Downloads/react-native-multibundler-master/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/cached-powers.o /Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/cached-powers.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ryan/Downloads/react-native-multibundler-master/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/bignum.o /Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/bignum.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ryan/Downloads/react-native-multibundler-master/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/bignum-dtoa.o /Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/third-party/double-conversion-1.1.6/src/bignum-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(8 failures)

Installing build/Build/Products/Debug-iphonesimulator/reactnative_multibundler.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/reactnative_multibundler.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/reactnative_multibundler.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:603:11)
    at Object.execFileSync (child_process.js:621:13)
    at Promise.then (/Users/ryan/Downloads/react-native-multibundler-master/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by smallnew** [comment]
试试这个，可能是新版xcode10 出现的问题
https://github.com/facebook/react-native/issues/21168#issuecomment-422431294
