### ISSUE TITLE
打的包不能正常运行，报Requiring unknown module "554".

### ISSUE THREAD

**Issue by martineden2017** [smallnew/react-native-multibundler#60]
10-18 15:57:32.973 25257-25298/com.reactnative_multibundler E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.reactnative_multibundler, PID: 25257
    com.facebook.jni.CppException: Requiring unknown module "554".
    
    v@index.android.bundle:1:1306
    index.android.bundle:5:36
    v@index.android.bundle:1:1474
    d@index.android.bundle:1:876
    global code@index.android.bundle:8:4
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)

**Comment by martineden2017** [comment]
用的是Tag：V2.2的版本

**Comment by zj740001680** [comment]
> 用的是Tag：V2.2的版本

这个问题你解决了嘛 请问

**Comment by smallnew** [comment]
使用最新的master分支试试
