### ISSUE TITLE
ios 分包加载异常

### ISSUE THREAD

**Issue by fypyxz** [smallnew/react-native-multibundler#62]
升级RN为0.61.2，分开打包，运行异常
按照流程一步一步生成基础包和业务包，运行结果
![601571911604_ pic](https://user-images.githubusercontent.com/4725045/67476047-d968fe80-f689-11e9-9561-8ea97e598511.jpg)

**Comment by smallnew** [comment]
现在升级到了0.61.5了，可以兼容了
