### ISSUE TITLE
有Mac版的拆包工具吗

### ISSUE THREAD

**Issue by ToryCrox** [smallnew/react-native-multibundler#63]
看到示例图上是用的mac的拆包的UI工具，但是没有看到下载链接，请问在哪儿？

**Comment by smallnew** [comment]
package-ui-bin目录下

**Comment by markdashi** [comment]
> package-ui-bin目录下

ui 打包工具下载下来只有 131 kb,无法解压，有办法解决吗

**Comment by smallnew** [comment]
因为lfs有1GB的限制，限制已经不使用lfs了，请到https://github.com/smallnew/RN-MultiBundler-UI获取最新的拆包工具
