### ISSUE TITLE
我直接设置第一个业务包是主入口，报com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly

### ISSUE THREAD

**Issue by jeromehan** [smallnew/react-native-multibundler#67]
`    <activity android:name=".demo.Buz1Activity" android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>`

**Comment by jeromehan** [comment]
<activity android:name=".demo.Buz1Activity" android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by zj740001680** [comment]
> ` <activity android:name=".demo.Buz1Activity" android:label="@string/app_name" > <intent-filter> <action android:name="android.intent.action.MAIN" /> <category android:name="android.intent.category.LAUNCHER" /> </intent-filter> </activity>`

请问你解决了吗

**Comment by jeromehan** [comment]
> > ` <activity android:name=".demo.Buz1Activity" android:label="@string/app_name" > <intent-filter> <action android:name="android.intent.action.MAIN" /> <category android:name="android.intent.category.LAUNCHER" /> </intent-filter> </activity>`
> 
> 请问你解决了吗

我把asyncActivity中的onCreated中的初始化代码放到 onResume()中就行了，不过不优雅，需要加标记处理比如onPause问题。主要是没办法保证初始化已经完成在onCreated周期中，所以采用这种方法

**Comment by smallnew** [comment]
可以参考最新的代码，加载代码已经为异步执行

**Comment by jeromehan** [comment]
> 可以参考最新的代码，加载代码已经为异步执行

最新代码 使用了`<activity android:name=".demo.Buz1Activity" android:label="@string/app_name" > <intent-filter> <action android:name="android.intent.action.MAIN" /> <category android:name="android.intent.category.LAUNCHER" /> </intent-filter> </activity>`  报 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactDelegate.onHostResume()' on a null object reference

注释了这两个方法的执行好了。。
![image](https://user-images.githubusercontent.com/19773879/72665602-050b4300-3a45-11ea-898a-5a1c8ecd8753.png)
