### ISSUE TITLE
ui 打包工具无法下载，可以放在网盘或者其他可以下载的地方不

### ISSUE THREAD

**Issue by reylen** [smallnew/react-native-multibundler#69]
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

该存储库超出了其数据配额。 负责LFS带宽的帐户应购买更多数据包以恢复访问。

ui 打包工具无法下载，可以放在网盘或者其他可以下载的地方不

**Comment by lufeion** [comment]
The same 
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/smallnew/react-native-multibundler.git/info/lfs'

**Comment by smallnew** [comment]
已经转到另外一个项目，看readme
