### ISSUE TITLE
请问开发的时候要怎么启动本地的server?

### ISSUE THREAD

**Issue by vanvanj** [smallnew/react-native-multibundler#7]
我这是ios的工程, 如果我在这个demo目录下直接npm start, 里面的模块会加载失败, 请问这种多模块的开发要怎么弄

**Comment by vanvanj** [comment]
方便加个QQ或者微信交流下么, 碰到比较多问题

**Comment by smallnew** [comment]
这个在分包时不支持，启动还是跟之前一样启动，就是原生代码需要自己修改下还是用原来的加载方式，先自己加个开关吧

**Comment by smallnew** [comment]
我后续看能否更改rn测试服务器加载js代码逻辑达到更好的体验

**Comment by Aptx4869-xd** [comment]
@smallnew 请问这个加载本地bundle还是加载局域网的js代码这个逻辑要怎么写的？我目前了解的是在getUseDeveloperSupport 这个方法里返回的布尔值控制的加载本地还是服务器，而且getUseDeveloperSupport的这个返回值一旦设置后就不能更改了的。

**Comment by smallnew** [comment]
DEBUG服务功能已完成
