### ISSUE TITLE
Swfit项目使用0.63.2版本创建RCTBridge对象会卡死

### ISSUE THREAD

**Issue by flyingbirdxyx** [smallnew/react-native-multibundler#92]
我的项目是iOS swift项目，升级到0.63.2后
执行 RCTBridge.init(bundleURL: Bundle.main.url(forResource: "platform.ios", withExtension: "bundle"), moduleProvider: nil, launchOptions: nil) 后， App就直接卡死了，请问有大佬遇到过类似问题吗？？

**Comment by CoderLinLee** [comment]
同样的问题，解决方案是啥

**Comment by flyingbirdxyx** [comment]
> 同样的问题，解决方案是啥

记不清了。。 看下BundleloadEventEmiter文件是不是添加到项目中了
